apiVersion: v1
kind: Service
metadata:
  name: rafka-headless
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: false
  selector:
    app: rafka-test-alpine
  ports:
  - name: rafka-port
    port: 8080
    targetPort: 8080
  - name: skytable-port
    port: 2003
    targetPort: 2003 