apiVersion: v1
kind: Service
metadata:
  name: rafka-test-alpine-service
spec:
  selector:
    app: rafka-test-alpine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
