apiVersion: v1
kind: Service
metadata:
  name: rafka-service
spec:
  type: NodePort
  selector:
    app: rafka-test-alpine
  ports:
  - name: rafka-port
    port: 8080
    targetPort: 8080
    nodePort: 30080
