apiVersion: v1
kind: ConfigMap
metadata:
  name: skytable-config
data:
  skytable.conf: |
    host = "0.0.0.0"
    port = 2003
    maxmem = "768mb"  # Leave some memory for the system
    persistence = false  # In-memory only 