apiVersion: apps/v1
kind: Deployment
metadata:
  name: rafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rafka
  template:
    metadata:
      labels:
        app: rafka
    spec:
      containers:
        - name: rafka-infra-test-1  # Changed to a valid name
          image: wyattgill/rafka_tests:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
