apiVersion: scylla.scylladb.com/v1alpha1
kind: ScyllaBackup
metadata:
  name: scheduled-backup
spec:
  cluster: scylla-cluster
  location: s3://your-backup-bucket/backups
  schedule: "0 */6 * * *"  # Every 6 hours
  retention:
    days: 30
  verification:
    enabled: true
    schedule: "0 4 * * *"  # Daily at 4 AM
  crossRegion:
    enabled: true
    regions:
      - name: backup-region
        bucket: s3://backup-region-bucket/backups 