apiVersion: apps/v1
kind: Service
metadata:
  name: scylla
  labels:
    app: scylla
spec:
  ports:
    - port: 9042
      name: cql
    - port: 9160
      name: thrift
  clusterIP: None # Headless service for StatefulSet
  selector:
    app: scylla
