apiVersion: v1
kind: Service
metadata:
  name: scylla-service
  namespace: default
spec:
  clusterIP: None                  # Headless service
  ports:
    - name: cql
      port: 9042                   # Cassandra Query Language (CQL) port
      targetPort: 9042
    - name: metrics
      port: 9180                   # Scylla metrics for Prometheus
      targetPort: 9180
  selector:
    app: scylla
