apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scylla
  labels:
    app: scylla
spec:
  serviceName: "scylla"
  replicas: 1
  selector:
    matchLabels:
      app: scylla
  template:
    metadata:
      labels:
        app: scylla
    spec:
      containers:
      - name: scylla
        image: scylladb/scylla:latest
        ports:
        - containerPort: 9042 # CQL port
        - containerPort: 9160 # Thrift port
        volumeMounts:
        - name: scylla-data
          mountPath: /var/lib/scylla
        resources:
          requests:
            memory: 80Mi
            cpu: 1
          limits:
            memory: 160Mi
            cpu: 2
      volumes:
      - name: scylla-data
        persistentVolumeClaim:
          claimName: scylla-data-pvc
