apiVersion: apps/v1
kind: Deployment
metadata:
  name: rafka
  namespace: rakfa-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rafka
  template:
    metadata:
      labels:
        app: rafka
    spec:
      containers:
      - name: rafka
        image: rafka:latest
        ports:
        - containerPort: 8080
