apiVersion: v1
kind: Service
metadata:
  name: scylladb
  namespace: rakfa-test
spec:
  selector:
    app: scylladb
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
  type: ClusterIP
