apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: rakfa-test
spec:
  selector:
    app: etcd
  ports:
    - protocol: TCP
      port: 2379
      targetPort: 2379
    - protocol: TCP
      port: 2380
      targetPort: 2380
  type: ClusterIP
