apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: rakfa-test
spec:
  serviceName: "etcd"
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:latest
        ports:
        - containerPort: 2379
        - containerPort: 2380
